### ISSUE TITLE
[Feature Request] Include feed's name in subject

### ISSUE THREAD

**Issue by ghost** [petronny/rssdrop#2]
This script is great for keeping up with rss feeds. I use it to get notified for new releases of projects hosted on github via the atom links. Unfortunately I do get quite lost when the subject is something like "0.8" and I can't seem to remember the developer's name in `From: ` either. It would be great, if I could have the meaningful name I assign to the feed via the config file or the `-a` switch display on the subject line, like they do in Mailing lists. Maybe even just as a config-option like `meaningful_names = true`, if you don't want to mess with the defaults.

For example, I have configured rssdrop to check the following feed:

```
[bower]
url = https://github.com/wangp/bower/releases.atom
```

The subjects I get are:

- 0.1
- 0.2
- 0.3
- ...

It would be great if they were:

- [bower] 0.1
- [bower] 0.2
- [bower] 0.3
- ...

Since "bower" is the meaningful name I assigned to that feed via `rssdrop -a bower https://github.com/wangp/bower/releases.atom`, this would help a lot in figuring out where that new thing in my mailbox came from.

I would get my hands dirty myself, but I  don't know any perl (yet), so any contribution I could make to solve this would probably just be a dirty hack taking way too long to write. I would greatly appreciate it, if you considered implementing this feature.

**Comment by petronny** [comment]
To re-fetch feeds you may need to delete `~/.rssdrop/{tmp,feed}` and your maildir.

**Comment by ghost** [comment]
Thanks a lot!
